apiVersion: v1
kind: Service
metadata:
  name: armadaui-react-app-service
spec:
  selector:
    app: armadaui-react-app
  ports:
    - protocol: TCP
      port: 80          # External port
      targetPort: 3000   # The container's port
  type: NodePort       # Exposes the service externally
